language: cpp
compiler:
  - gcc
  - clang

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  #- if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get update; sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main';wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -;sudo apt-get update; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -y clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script: make
